# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff9d9681d8c0bba9118fc56e7cbcd2ec0a4e7dee6f13c608f8ae17a5acce7e248bab9d3ac0bb237e73f9d3dbf4d27934da71e79a61187fa662a204fdb1d3b94

test:
  secret_key_base: 888b9de91bc22479ec28da7c12590d16be85577da6ded352733b06d05e7a6db7848b31f8755d037fd0a23f59ea2a06f0818fa83664de5548bb2d90fd4d8a6bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
